### ISSUE TITLE
What is the name of the database host of this project?

### ISSUE THREAD

**Issue by seti1212** [theHocineSaad/linatabra3#10]
Hi
What is the name of the database host of this project?
1: local
2: amazon
3: mongoDB
4: and...

**Comment by theHocineSaad** [comment]
> Hi What is the name of the database host of this project? 1: local 2: amazon 3: mongoDB 4: and...

I used MySQL and it was installed on my computer, I used Laragon to be specific.
But you can use any DBMS and host it anywhere you want.
Have a look at: https://laravel.com/docs/9.x/database#configuration
