### ISSUE TITLE
How To Change Wilaya and Daira Value  [Only Home Page section]

### ISSUE THREAD

**Issue by ghost** [theHocineSaad/linatabra3#9]
I have changed the name from wilayaseeder and dairaseeder file with database , still it shows default wilaya and daira .but Only Reg section shows Changes Wilaya and Daira value..

**Comment by theHocineSaad** [comment]
@dkupdate I think it's because you didn't clear the cache, run this command and check again:
`php artisan cache:clear`
Please let me know if this fixed your issue.

**Comment by ghost** [comment]
Thank You So Much . Working❤️
